### ISSUE TITLE
scalar reference in new() is too lazy

### ISSUE THREAD

**Issue by cfaber** [rjbs/Email-Simple#10]
The scalar reference check in new() is too lazy, ref will return true if a blessed reference of text data is passed to it resulting in a failure later in the code.

`  my $text_ref = ref $text ? $text : \$text;
[scalar_reference_fix.patch.txt](https://github.com/rjbs/Email-Simple/files/116385/scalar_reference_fix.patch.txt)

`

**Comment by rjbs** [comment]
I pushed up 15c47f4.  How's that look?

I think I want to improve the checks, though.

**Comment by cfaber** [comment]
Sorry, not seeing that commit, did it make it into the public repo?

**Comment by rjbs** [comment]
not to github, only another mirror, because I was dumb, sorry

should be better now
