### ISSUE TITLE
warning in header_raw

### ISSUE THREAD

**Issue by hoytech** [rjbs/Email-Simple#12]
Not a big deal but FYI:

<pre>
Use of uninitialized value in lc at /usr/local/share/perl5/Email/Simple/Header.pm line 204.
</pre>

If it helps to get the actual email headers I could probably find them...

<pre>
$ cpanm Email::Simple --sudo
Email::Simple is up to date. (2.210)
</pre>

**Comment by rjbs** [comment]
Did this come from building a new message or parsing a string?  I made a quick go at it, but couldn't reproduce the problem.

**Comment by hoytech** [comment]
Sorry for the crappy bug report.

It was when parsing a string. Looks to be related to multi-part MIME in some way:

<pre>
use Email::MIME;

Email::MIME->new(
q{From junk@junk.com
Content-Type: multipart/mixed; boundary="=-=-="

--=-=-=

test

--=-=-=

});
</pre>

results in this:

<pre>
Use of uninitialized value in lc at /usr/local/share/perl5/Email/Simple/Header.pm line 204.
Use of uninitialized value in lc at /usr/local/share/perl5/Email/Simple/Header.pm line 204.
</pre>

I have no idea if this email is invalid in some way, just that I saw a heap of these warnings when parsing a largish archive of real-world emails.

Thanks!

**Comment by rjbs** [comment]
Okay, thanks.  So, this is a bug in Email::MIME, not Email::Simple.  It looks like maybe it always thinks the line after the boundary is a header, and never blank.  That's probably required by the spec, since I believe every part needs a C-T.  I'll look into fixing the warning, anyway, of course!

**Comment by pali** [comment]
There is really bug in Email::Simple. I created patch with tests: https://github.com/rjbs/Email-Simple/pull/14

**Comment by rjbs** [comment]
Thanks, applied #14.
