### ISSUE TITLE
Deep recursion on subroutine "Email::Simple::Header::header"

### ISSUE THREAD

**Issue by eserte** [rjbs/Email-Simple#8]
With newest version I observe deep recursion errors:
```
Deep recursion on subroutine "Email::Simple::Header::header" at /home/travis/perl5/perlbrew/perls/5.20/lib/site_perl/5.20.0/Email/MIME/Header.pm line 54.
Deep recursion on subroutine "Email::MIME::Header::header_raw" at /home/travis/perl5/perlbrew/perls/5.20/lib/site_perl/5.20.0/Email/Simple/Header.pm line 212.
```
(Sample broken travis-ci build: https://travis-ci.org/eserte/bbbike/jobs/55911163 )

**Comment by eserte** [comment]
Downgrading Email::Simple from 2.204 to 2.203 helps (sample build: https://travis-ci.org/eserte/bbbike/jobs/55982416 )

**Comment by rjbs** [comment]
Thanks, I'm sure I tested this!  I wonder what I missed.  I will correct this today, whatever the case.

**Comment by rjbs** [comment]
I've made a new release that just reverts these changes for now. I'll sort things out more thoroughly tonight.

**Comment by rjbs** [comment]
I've released a new new version, with the changes back in, but now in a way that won't cause the downstream failure.

I am certain that I tried to test this, before, and I must have just bungled a step.  Thanks *very* much for the quick notification!

**Comment by eserte** [comment]
Everything's well, just tested with Email-Simple-2.206 (<https://travis-ci.org/eserte/bbbike/jobs/56147937>). Thanks!
