### ISSUE TITLE
RT issue 2478 does not exist

### ISSUE THREAD

**Issue by madsen** [rjbs/Email-Simple#9]
The CAVEATS section of the docs says to "consult RT issue 2478, <http://rt.cpan.org/NoAuth/Bug.html?id=2478>."

However, visiting that link says "Could not load ticket 2478" and there's no such bug in [the Email-Simple queue](https://rt.cpan.org/Dist/Display.html?Queue=Email-Simple).

**Comment by rjbs** [comment]
Weird, thanks.  I've just deleted the text in git.
